# Generated by Django 6.0.3 on 2026-05-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_coupon_book_stock_order_discount_amount_order_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'COD'), ('vnpay', 'VNPay'), ('momo', 'Momo')], default='cod', max_length=20),
        ),
    ]
