# Generated by Django 6.0.3 on 2026-05-16 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_content_text_book_is_digital_readingprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_digital_purchase',
            field=models.BooleanField(default=False, help_text='Đánh dấu nếu đây là đơn mua bản E-book'),
        ),
    ]
