# Generated by Django 6.0.3 on 2026-06-02 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_admin_audit_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='content_html',
            field=models.TextField(blank=True, help_text='Nội dung sách dạng HTML đã lọc, có thể chứa ảnh minh họa'),
        ),
    ]
