# Generated by Codex on 2026-06-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0009_order_idempotency_key_order_paid_at_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                fields=("transaction_id",),
                condition=models.Q(transaction_id__isnull=False) & ~models.Q(transaction_id=""),
                name="uniq_order_transaction_id_not_blank",
            ),
        ),
    ]
